listener 8883
allow_anonymous true
cafile C:/Ohm_Project/mosquitto_certs/ca.crt
certfile C:/Ohm_Project/mosquitto_certs/server.crt
keyfile C:/Ohm_Project/mosquitto_certs/server.key
tls_version tlsv1.2

listener 1883
allow_anonymous true
